### ISSUE TITLE
Data.IntervalMap exports Prelude functions instead of its own definitions

### ISSUE THREAD

**Issue by bscottm** [bokesan/IntervalMap#3]
I'm sure it's a minor oversight: Is Data.IntervalMap.Strict's `lookup` function really supposed to take a list of `assocs`?

    import qualified Data.IntervalMap.Strict as IM

    fun :: IM.IntervalMap Int String
    fun ivmap k v =
      case IM.lookup k ivmap of
        Just _x -> "Good"
        Nothing -> "Bad"

GHC error:

     Couldn't match expected type ‘[(Int, IM.IntervalMap Int String)]'
                   with actual type ‘IM.IntervalMap Int String’

**Comment by bscottm** [comment]
Reading through the code, it looks like you're hiding `lookup` from `Data.IntervalMap.Generic.Strict` unnecessarily and re-exporting Prelude's `lookup`.

It's possible to work around this "bug" by importing `Data.IntervalMap.Generic.Strict` and doing what `Data.IntervalMap.Strict` does:

```
import qualified Data.IntervalMap.Generic.Strict as IM
import qualified Data.IntervalMap.Interval as I

type MyIntervalMap k v = IM.IntervalMap (I.Interval k) v

getSomething ivmap k =
  case IM.lookup (I.ClosedInterval k k) ivmap of
    -- Work through Maybe cases here...
```

It's a plausible workaround, but the "bug" in `Data.IntervalMap.Strict` remains.

**Comment by bokesan** [comment]
Good catch - thanks for reporting this! I'm on vacation right now, so I'll only get to fix this in a week or so.

**Comment by bokesan** [comment]
It's not only `lookup`, but also `null`, `filter`, `map`, `foldr`, `foldl`.
