### ISSUE TITLE
Please add lookupLE and lookupGE

### ISSUE THREAD

**Issue by jason-johnson** [bokesan/IntervalMap#4]
The interface here is close to the standard Data.Map but it lacks lookupLE (lookup less than or equal) and lookupGE (greater or equal).  I am using intervals to cover time periods but there are times that no interval covers, so in that case I need to be able to find the closest match on either side.  I realise I could use split for this but for what I want I would need to do something like

IMap.split i >>> IMap.findMax *** IMap.findMin $ imap

but it may be possible to do this more efficiently in the library.  If it is not, this issue can be closed.

**Comment by bokesan** [comment]
It can be done much more efficiently, so I'll probably add the four `lookupXX` functions.

But could you still describe your use-case a bit more? If the "closest" interval is defined to be the one with the closest endpoint, `findMax` would only work if the map contains no overlapping intervals. You would need to use `splitAt` or `splitIntersecting` and `findLast` in that case. I'm always looking for interval-specific use-cases, so I'm wondering if a variant of e.g. `splitAt` might be a better fit than just adding the regular map key lookups.

**Comment by jason-johnson** [comment]
Basically, I use an interval map to hold time zone transition information in the target intervals that the zone offset was in effect. So, for example, the central Europe zone will have intervals with a 1 hour gap every summer and 1 hour with an overlap of 2 offsets every fall.

So that means for most times there will just be one offset in effect but there are two ambiguous cases: in fall there will be 1 hour where two offsets actually apply and in spring there will be one hour that does not exist in the interval map. In my library there is a convenience function that has a strategy to deal with each case: for the overlap case we pick the first offset and for the gap we need to figure out the time difference between the offset before the non-existent time and the offset after. We subtract the earlier from the later (which must be larger or there would be no gap) and add that time to the user requested time. In general this should add one hour to the requested time but there are cases where it will be difference (e.g. political zone changes). 

So what I need, for the case that i already know a gap exists, is a way of getting the closest interval before the time and the closest after.

**Comment by bokesan** [comment]
A new release including `lookupLE` and friends is up on Hackage.
