### ISSUE TITLE
Empty intervals do not have a consistent interpretation with respect to `overlaps` and `intersecting`

### ISSUE THREAD

**Issue by danmatichuk** [bokesan/IntervalMap#9]
Any open or half-open interval with the same lower and upper bound should be considered empty (i.e. `(x,x]`, `[x,x)` and `(x,x)`). The function `IntervalMap.isEmpty` agrees with this interpretation, where `IntervalMap.isEmpty (IntervalCO 1 1)` is `True`. However, this is not consistent with the results of `IntervalMap.intersecting` or `IntervalMap.overlaps`, since an empty interval should never intersect or overlap with any other interval.

Current behavior: `IntervalMap.overlaps (IntervalCO 1 1) (InvervalCO 0 2)` is `True` 
Expected behavior: `IntervalMap.overlaps (IntervalCO 1 1) (InvervalCO 0 2)` should  be `False`

Current behavior :`IntervalMap.intersecting (fromList [(IntervalCO 0 2, "0_2")]) (IntervalCO 1 1)` is `[(IntervalCO 0 2, "0_2")]`
Expected behavior: `IntervalMap.intersecting (fromList [(IntervalCO 0 2, "0_2")]) (IntervalCO 1 1)` should be `[]`

**Comment by bokesan** [comment]
Thanks for reporting this! I'll look into it asap.
